compatibility_date = "2024-11-01"
name = "aiwaan"

pages_build_output_dir = "build/client"

[env.production.vars]
VITE_APPWRITE_DATABASE_ID = "aiwaan"
VITE_APPWRITE_ENDPOINT = "https://fra.cloud.appwrite.io/v1"
VITE_APPWRITE_PROJECT_ID = "685d47d200131e659efb"
VITE_APPWRITE_STORAGE_BUCKET_ID = "your-storage-bucket-id"
